import { jsPDF } from "jspdf";
import type { Audit } from "@/lib/types";
import { getDomain } from "@/lib/audit-config";

/**
 * Client-side PDF export of a completed audit report. Renders a clean,
 * multi-section document with scores, issues and recommendations.
 */
export function exportAuditToPdf(audit: Audit) {
  const report = audit.report;
  if (!report) throw new Error("Audit has no report to export.");

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const ensureSpace = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const heading = (text: string, size = 14) => {
    ensureSpace(size + 12);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(size);
    doc.setTextColor(17, 24, 39);
    doc.text(text, margin, y);
    y += size + 8;
  };

  const paragraph = (text: string, size = 10) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(size);
    doc.setTextColor(55, 65, 81);
    const lines = doc.splitTextToSize(text, contentWidth) as string[];
    lines.forEach((line) => {
      ensureSpace(size + 4);
      doc.text(line, margin, y);
      y += size + 4;
    });
  };

  // --- Cover header ---
  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, pageWidth, 96, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Product Audit Studio", margin, 50);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(audit.profile.productName, margin, 70);
  y = 130;

  // --- Score + headline ---
  doc.setFont("helvetica", "bold");
  doc.setFontSize(40);
  doc.setTextColor(99, 102, 241);
  doc.text(`${report.overallScore}`, margin, y);
  doc.setFontSize(12);
  doc.setTextColor(107, 114, 128);
  doc.text("/ 100 overall score", margin + 64, y);
  y += 28;

  heading(report.headline, 13);
  paragraph(report.summary);
  y += 8;

  // --- Domain scores ---
  heading("Pillar scores");
  report.domainScores.forEach((d) => {
    ensureSpace(28);
    const title = getDomain(d.domain).title;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(31, 41, 55);
    doc.text(`${title}`, margin, y);
    doc.text(`${d.score}/100`, margin + contentWidth - 50, y);
    // progress bar
    y += 6;
    doc.setFillColor(229, 231, 235);
    doc.roundedRect(margin, y, contentWidth, 6, 3, 3, "F");
    doc.setFillColor(99, 102, 241);
    doc.roundedRect(margin, y, (contentWidth * d.score) / 100, 6, 3, 3, "F");
    y += 18;
  });
  y += 8;

  // --- Strengths ---
  if (report.strengths.length) {
    heading("Strengths");
    report.strengths.forEach((s) => paragraph(`•  ${s}`));
    y += 8;
  }

  // --- Issues ---
  if (report.issues.length) {
    heading("Key issues");
    report.issues.forEach((issue) => {
      ensureSpace(40);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(185, 28, 28);
      doc.text(
        `[${issue.severity.toUpperCase()}] ${issue.title}`,
        margin,
        y,
      );
      y += 14;
      paragraph(issue.description);
      y += 4;
    });
    y += 4;
  }

  // --- Recommendations ---
  if (report.recommendations.length) {
    heading("Recommendations");
    report.recommendations.forEach((rec) => {
      ensureSpace(40);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(22, 101, 52);
      doc.text(rec.title, margin, y);
      y += 14;
      paragraph(
        `${rec.description}  (Impact: ${rec.impact}, Effort: ${rec.effort})`,
      );
      y += 4;
    });
  }

  // --- Footer ---
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(
      `Generated by Product Audit Studio • ${new Date(report.generatedAt).toLocaleDateString()} • Page ${i}/${pageCount}`,
      margin,
      doc.internal.pageSize.getHeight() - 24,
    );
  }

  const filename = `${audit.profile.productName || "product"}-audit.pdf`
    .toLowerCase()
    .replace(/[^a-z0-9.-]+/g, "-");
  doc.save(filename);
}
