import { jsPDF } from "jspdf";
import type { Audit } from "@/lib/types";
import type { DimensionResult } from "@/lib/audit/auditTypes";

/**
 * Client-side PDF export of a completed audit. Renders a clean, multi-section
 * document with the maturity stage, category and dimension scores, priorities
 * and recommendations.
 */
export function exportAuditToPdf(audit: Audit) {
  const report = audit.report;
  if (!report) throw new Error("Audit has no report to export.");

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const ensureSpace = (needed: number) => {
    if (y + needed > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const heading = (text: string, size = 14) => {
    ensureSpace(size + 12);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(size);
    doc.setTextColor(17, 24, 39);
    doc.text(text, margin, y);
    y += size + 8;
  };

  const paragraph = (text: string, size = 10) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(size);
    doc.setTextColor(55, 65, 81);
    const lines = doc.splitTextToSize(text, contentWidth) as string[];
    lines.forEach((line) => {
      ensureSpace(size + 4);
      doc.text(line, margin, y);
      y += size + 4;
    });
  };

  const scoreBar = (label: string, score: number) => {
    ensureSpace(28);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(31, 41, 55);
    doc.text(label, margin, y);
    doc.text(`${score}/100`, margin + contentWidth - 50, y);
    y += 6;
    doc.setFillColor(229, 231, 235);
    doc.roundedRect(margin, y, contentWidth, 6, 3, 3, "F");
    const [r, g, b] =
      score >= 70 ? [22, 163, 74] : score >= 45 ? [202, 138, 4] : [220, 38, 38];
    doc.setFillColor(r, g, b);
    doc.roundedRect(margin, y, (contentWidth * score) / 100, 6, 3, 3, "F");
    y += 18;
  };

  // --- Cover header ---
  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, pageWidth, 96, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Product Audit Studio", margin, 50);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(audit.profile.productName, margin, 70);
  y = 130;

  // --- Score + maturity ---
  doc.setFont("helvetica", "bold");
  doc.setFontSize(40);
  doc.setTextColor(99, 102, 241);
  doc.text(`${report.overallScore}`, margin, y);
  doc.setFontSize(12);
  doc.setTextColor(107, 114, 128);
  doc.text(`/ 100  ·  ${report.maturityStage}`, margin + 64, y);
  y += 28;

  heading(report.headline, 13);
  paragraph(report.summary);
  paragraph(report.maturitySummary);
  y += 8;

  // --- Category scores ---
  heading("Category scores");
  report.categories.forEach((c) => scoreBar(c.title, c.score));
  y += 8;

  // --- Dimension scores ---
  heading("Dimension scores");
  report.dimensions.forEach((d) => scoreBar(d.title, d.score));
  y += 8;

  // --- Top priorities ---
  if (report.topPriorities.length) {
    heading("Top priorities");
    report.topPriorities.forEach((d: DimensionResult) => {
      ensureSpace(48);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(185, 28, 28);
      doc.text(`[${d.priority.toUpperCase()}] ${d.title}`, margin, y);
      y += 14;
      paragraph(d.explanation);
      d.recommendations.forEach((r) => paragraph(`•  ${r}`));
      d.nextActions.forEach((a) => paragraph(`→  ${a}`));
      y += 6;
    });
  }

  // --- Strengths ---
  if (report.strengths.length) {
    heading("Strengths");
    report.strengths.forEach((d) => {
      ensureSpace(24);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(22, 101, 52);
      doc.text(`${d.title} — ${d.score}/100`, margin, y);
      y += 14;
      paragraph(d.explanation);
      y += 4;
    });
  }

  // --- Footer ---
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(
      `Generated by Product Audit Studio · ${new Date(report.generatedAt).toLocaleDateString()} · Page ${i}/${pageCount}`,
      margin,
      doc.internal.pageSize.getHeight() - 24,
    );
  }

  const filename = `${audit.profile.productName || "product"}-audit.pdf`
    .toLowerCase()
    .replace(/[^a-z0-9.-]+/g, "-");
  doc.save(filename);
}
